esphome:
  name: espchip2
  friendly_name: espchip2

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:


ota:
  - platform: esphome


wifi:
  ssid: WiFi-5F80-extend2
  password: "*******"
  power_save_mode: none


  # Enable fallback hotspot (captive portal) in case wifi connection fails


captive_portal:
    
